### ISSUE TITLE
同じ条件を OR してそう

### ISSUE THREAD

**Issue by a01sa01to** [sor4chi/maxisu-isucon10q#5]
https://github.com/sor4chi/maxisu-isucon10q/blob/2ffe444d60006c5f1cb81c48febd027dd991dd0a/webapp/go/main.go#L840

**Comment by Ryoga-exe** [comment]
https://github.com/sor4chi/maxisu-isucon10q/blob/2ffe444d60006c5f1cb81c48febd027dd991dd0a/webapp/go/main.go#L841

直後のここを読むと 2 辺を超えるようなものをクエリしてそう

**Comment by Ryoga-exe** [comment]
`w, min(h, d)`, `h, min(w, d)`, `d, min(h, w)` にまとめられそう…？

**Comment by a01sa01to** [comment]
なるほど...？
